# -*- coding: utf-8 -*-
import threading
import tkinter as tk
from multiprocessing import Process
# Form implementation generated from reading ui file 'mainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from threading import Thread
from tkinter import filedialog

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QHeaderView

from excel import Excel
from qianniu import Qianniu


class Ui_MainWindow(object):
    excel = Excel()
    qianniu = Qianniu()

    # 线程池
    processpool = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 601))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dataFrom = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.dataFrom.setEnabled(True)
        self.dataFrom.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.dataFrom.setAutoFillBackground(True)
        self.dataFrom.setObjectName("dataFrom")
        self.dataFrom.setColumnCount(2)
        self.dataFrom.setRowCount(1)
        # 设置第一行颜色
        self.dataFrom.horizontalHeader().setStyleSheet(
            "QHeaderView::section{background-color:rgb(255, 255, 255);font:11pt '宋体';color: black;};")
        item = QtWidgets.QTableWidgetItem()
        self.dataFrom.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataFrom.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.dataFrom)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 90, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.yearEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.yearEdit.setGeometry(QtCore.QRect(500, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yearEdit.setFont(font)
        self.yearEdit.setText("")
        self.yearEdit.setObjectName("yearEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 125, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.monthEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.monthEdit.setGeometry(QtCore.QRect(600, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.monthEdit.setFont(font)
        self.monthEdit.setObjectName("monthEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 125, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.dayEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dayEdit.setGeometry(QtCore.QRect(700, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dayEdit.setFont(font)
        self.dayEdit.setObjectName("dayEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(770, 125, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.yearEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.yearEdit_2.setGeometry(QtCore.QRect(500, 215, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yearEdit_2.setFont(font)
        self.yearEdit_2.setObjectName("yearEdit_2")
        self.dayEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.dayEdit_2.setGeometry(QtCore.QRect(700, 215, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dayEdit_2.setFont(font)
        self.dayEdit_2.setObjectName("dayEdit_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(670, 220, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 220, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.monthEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.monthEdit_2.setGeometry(QtCore.QRect(600, 215, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.monthEdit_2.setFont(font)
        self.monthEdit_2.setObjectName("monthEdit_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(510, 185, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(770, 220, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(570, 520, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.startBtn.setFont(font)
        self.startBtn.setObjectName("startBtn")
        self.startBtn.clicked.connect(self.t_coll)
        self.uploadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.uploadBtn.setGeometry(QtCore.QRect(570, 440, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uploadBtn.setFont(font)
        self.uploadBtn.setObjectName("uploadBtn")
        self.uploadBtn.clicked.connect(self.upload_file)
        self.chooseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.chooseBtn.setGeometry(QtCore.QRect(720, 350, 70, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chooseBtn.setFont(font)
        self.chooseBtn.setObjectName("chooseBtn")
        self.chooseBtn.clicked.connect(self.choose_file)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(490, 280, 311, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(610, 300, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.fileLocation = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLocation.setGeometry(QtCore.QRect(500, 350, 200, 30))
        self.fileLocation.setObjectName("fileLocation")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(490, 400, 311, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "淘宝报表解析"))
        item = self.dataFrom.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "账号"))
        item = self.dataFrom.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "密码"))
        self.label.setText(_translate("MainWindow", "付款时间"))
        self.label_2.setText(_translate("MainWindow", "起始时间:"))
        self.label_3.setText(_translate("MainWindow", "年"))
        self.label_4.setText(_translate("MainWindow", "月"))
        self.label_5.setText(_translate("MainWindow", "日"))
        self.label_6.setText(_translate("MainWindow", "月"))
        self.label_7.setText(_translate("MainWindow", "年"))
        self.label_8.setText(_translate("MainWindow", "结束时间:"))
        self.label_9.setText(_translate("MainWindow", "日"))
        self.startBtn.setText(_translate("MainWindow", "开始采集"))
        self.uploadBtn.setText(_translate("MainWindow", "上传"))
        self.chooseBtn.setText(_translate("MainWindow", "选择"))
        self.label_10.setText(_translate("MainWindow", "文件位置"))
        self.fileLocation.setPlaceholderText(_translate("MainWindow", "Excel的下载位置"))
        self.yearEdit.setPlaceholderText(_translate("MainWindow", "2024"))
        self.monthEdit.setPlaceholderText(_translate("MainWindow", "01"))
        self.dayEdit.setPlaceholderText(_translate("MainWindow", "01"))
        self.yearEdit_2.setPlaceholderText(_translate("MainWindow", "2024"))
        self.monthEdit_2.setPlaceholderText(_translate("MainWindow", "01"))
        self.dayEdit_2.setPlaceholderText(_translate("MainWindow", "01"))

    account = []
    passwd = []

    def upload_file(self):
        '''
        上传文件
        :return:
        '''
        self.uploadBtn.setEnabled(False)
        # 实例化
        root = tk.Tk()
        root.withdraw()
        # 获取文件夹路径
        f_path = filedialog.askopenfilename()
        self.uploadBtn.setEnabled(True)
        # print('\n获取的文件地址：', f_path)
        if f_path:
            self.account.clear()
            self.passwd.clear()
            self.account, self.passwd = self.excel.get_acc(f_path)
            self.dataFrom.setRowCount(len(self.account))

            t1 = threading.Thread(target=self.fill_table)
            t1.start()

    def choose_file(self):
        '''
        选择文件存储路径
        :return:
        '''
        self.chooseBtn.setEnabled(False)
        # 实例化
        root = tk.Tk()
        root.withdraw()
        # 获取文件夹路径
        f_path = filedialog.askdirectory()
        f_path = f_path.replace('/', '\\')
        self.chooseBtn.setEnabled(True)
        # 显示到输入框里
        self.fileLocation.setText(f_path)

    def fill_table(self):
        # 读取空行
        for i in range(len(self.account)):
            item1 = QTableWidgetItem(self.account[i])
            self.dataFrom.setItem(i, 0, item1)
            item2 = QTableWidgetItem(self.passwd[i])
            self.dataFrom.setItem(i, 1, item2)
            self.dataFrom.viewport().update()

    def t_coll(self):
        t2 = Thread(target=self.collect)
        t2.start()

    def collect(self):
        # 起始时间
        s_year = self.yearEdit.text() if not self.yearEdit.text() == '' else '2024'
        s_month = self.monthEdit.text() if not self.monthEdit.text() == '' else '01'
        s_day = self.dayEdit.text() if not self.dayEdit.text() == '' else '01'

        # s_year = '2024'
        # s_month = '02'
        # s_day = '01'

        # 结束时间
        e_year = self.yearEdit_2.text() if not self.yearEdit_2.text() == '' else '2024'
        e_month = self.monthEdit_2.text() if not self.monthEdit_2.text() == '' else '03'
        e_day = self.dayEdit_2.text() if not self.dayEdit_2.text() == '' else '01'

        # e_year = '2024'
        # e_month = '02'
        # e_day = '29'

        # 文件位置
        location = self.fileLocation.text()
        # location = 'D:\Download'
        self.qianniu.download = location

        if location == '':
            return

        self.startBtn.setText('采集中...')
        self.startBtn.setEnabled(False)
        # 获取信息
        s_date = f'{s_year}-{s_month}-{s_day}'
        e_date = f'{e_year}-{e_month}-{e_day}'

        # 休眠时间
        time = 0
        # 使用多进程执行
        try:
            for i in range(len(self.account)):
                time += 5
                p = Process(target=self.qianniu.multi_pro, args=(time, location, self.account[i], self.passwd[i], s_date, e_date))
                p.start()
                self.processpool.append(p)

            for i in self.processpool:
                i.join()
        finally:
            self.startBtn.setText('开始采集')
            self.startBtn.setEnabled(True)


        # for i in range(len(self.account)):
        #     self.startBtn.setText('采集中...')
        #     self.startBtn.setEnabled(False)
        #     try:
        #         # 登录
        #         self.qianniu.login(account=self.account[i], passwd=self.passwd[i])
        #         # 获取信息
        #         s_date = f'{s_year}-{s_month}-{s_day}'
        #         e_date = f'{e_year}-{e_month}-{e_day}'
        #         sum_money, data_state, order_state = self.qianniu.get_info(start_time=s_date, end_time=e_date)
        #         self.qianniu.parse_excel(location, self.account[i], self.passwd[i], sum_money, data_state, order_state)
        #     finally:
        #         self.startBtn.setText('开始采集')
        #         self.startBtn.setEnabled(True)
